<a href="https://colab.research.google.com/github/aeyjeyaryan/Deep-Learning/blob/main/Word_Embedding_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
z = open("dataset.txt")
y = z.read()
print(y)
z.close()

The sun sets over the horizon.
A cat sleeps on the windowsill.
She reads a book by the fireplace.
The dog barks at the mailman.
The flowers bloom in the garden.
He drinks coffee in the morning.
The car speeds down the highway.
Birds sing in the early dawn.
The child plays with a toy train.
The rain falls softly on the roof.



In [5]:
sent = list(y.split("\n"))

In [6]:
sent

['The sun sets over the horizon.',
 'A cat sleeps on the windowsill.',
 'She reads a book by the fireplace.',
 'The dog barks at the mailman.',
 'The flowers bloom in the garden.',
 'He drinks coffee in the morning.',
 'The car speeds down the highway.',
 'Birds sing in the early dawn.',
 'The child plays with a toy train.',
 'The rain falls softly on the roof.',
 '']

In [8]:
from tensorflow.keras.preprocessing.text import one_hot


In [11]:
voc_size=10000

In [12]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

#this gives index to each and every word

[[1836, 571, 8884, 7714, 1836, 9424], [4701, 7813, 663, 8485, 1836, 6601], [9374, 4257, 4701, 9355, 4430, 1836, 3278], [1836, 3834, 9805, 7066, 1836, 6830], [1836, 6556, 5528, 7562, 1836, 9139], [6245, 6493, 6981, 7562, 1836, 7880], [1836, 5804, 8581, 6694, 1836, 7750], [9233, 9055, 7562, 1836, 8442, 115], [1836, 8156, 5182, 7308, 4701, 8599, 8227], [1836, 9663, 3937, 5938, 8485, 1836, 6397], []]


In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
#since the words are not of equal length we user padding technique i.e pre here that adds zeros to the front to make the sentences of equal length

[[   0    0 1836  571 8884 7714 1836 9424]
 [   0    0 4701 7813  663 8485 1836 6601]
 [   0 9374 4257 4701 9355 4430 1836 3278]
 [   0    0 1836 3834 9805 7066 1836 6830]
 [   0    0 1836 6556 5528 7562 1836 9139]
 [   0    0 6245 6493 6981 7562 1836 7880]
 [   0    0 1836 5804 8581 6694 1836 7750]
 [   0    0 9233 9055 7562 1836 8442  115]
 [   0 1836 8156 5182 7308 4701 8599 8227]
 [   0 1836 9663 3937 5938 8485 1836 6397]
 [   0    0    0    0    0    0    0    0]]


In [18]:
dim = 15

In [19]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse') #mean squared error(performance metrics)

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 138ms/step


array([[[ 3.38924192e-02, -2.70110965e-02, -2.57042181e-02,
          1.23032182e-03, -3.73193622e-02,  4.44330014e-02,
          1.50603764e-02,  3.14544179e-02,  8.68059695e-04,
         -2.73707509e-02],
        [ 3.38924192e-02, -2.70110965e-02, -2.57042181e-02,
          1.23032182e-03, -3.73193622e-02,  4.44330014e-02,
          1.50603764e-02,  3.14544179e-02,  8.68059695e-04,
         -2.73707509e-02],
        [ 1.32051818e-02, -2.86723301e-03,  4.87760194e-02,
         -1.14278086e-02, -1.32165775e-02,  1.71943568e-02,
         -1.27454288e-02,  1.29192732e-02, -4.70817089e-04,
         -5.31683117e-03],
        [ 4.75525297e-02,  3.05634402e-02, -1.18426792e-02,
         -7.79583305e-03,  2.11252831e-02,  4.35580052e-02,
         -4.08216491e-02, -2.14246269e-02, -4.69002388e-02,
         -7.45607540e-03],
        [ 4.42276150e-03,  3.37431468e-02, -4.62632291e-02,
          2.16904916e-02, -3.65329497e-02, -4.25497554e-02,
         -3.85107026e-02, -4.84395772e-04, -2.281903

Process of performing word embedding
1. get dataset
2. One hot representation - index to each word
3. Embedding layers to form embedding matrix
4. Embedding matrix, vocb_size = 10000, dim = 10
